### ISSUE TITLE
Piped wants to write inside the site-packages

### ISSUE THREAD

**Issue by martinvilu** [foundit/Piped#1]
Fedora 13 - Python 2.6.4
Unable to complete the first step of the tutorial
Somehow the library wants to write inside the site-packages...
(installed with easy_install)

Any pointers, besides using a newer python or the devel version?

Traceback
[martin@cabctr15 piped]$ piped -nc tutorial.yaml -D
2011-06-30 16:00:08-0300 [-] Log opened.
2011-06-30 16:00:08-0300 [-] twistd 10.2.0 (/usr/bin/python 2.6.4) starting up.
2011-06-30 16:00:08-0300 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2011-06-30 16:00:08-0300 [-] [CRITICAL] Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/piped-0.1.0-py2.6.egg/piped/plugin.py", line 65, in load_plugins
        for plugin in self._get_plugins_from_package(package):
      File "/usr/lib/python2.6/site-packages/piped-0.1.0-py2.6.egg/piped/plugin.py", line 118, in _get_plugins_from_package
        for plugin in getPlugins(self.plugin_interface, reflect.namedAny(sub_package_name)):
      File "/usr/lib/python2.6/site-packages/piped-0.1.0-py2.6.egg/piped/plugin.py", line 31, in getPlugins
        for plugin in twisted_plugin.getPlugins(interface, package):
      File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 199, in getPlugins
        allDropins = getCache(package)
    --- <exception caught here> ---
      File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/plugin.py", line 178, in getCache
        dropinPath.setContent(pickle.dumps(dropinDotCache))
      File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 765, in setContent
        f = sib.open('w')
      File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 515, in open
        return self.create()
      File "/usr/lib/python2.6/site-packages/Twisted-10.2.0-py2.6-linux-i686.egg/twisted/python/filepath.py", line 791, in create
        fdint = os.open(self.path, _CREATE_FLAGS)
    exceptions.OSError: [Errno 13] Permission denied: '/usr/lib/python2.6/site-packages/piped-0.1.0-py2.6.egg/piped/providers/test/VBcnPcyVq9XPU5S_dropin.cache.new'

2011-06-30 16:00:08-0300 [-] Main loop terminated.
2011-06-30 16:00:08-0300 [-] Server Shut Down.

**Comment by nkvoll** [comment]
We use the plugin support in Twisted to load plugins (processors and providers). Twisted atomically stores a dropin.cache file any folder containing a plugin, which fails since the current user does not have the rights to write these files in the global package directories.

This might be an issue with Twisted, which we rely heavily on, or maybe a missing setup-time hook to ensure that these files gets generated during install.

Until a general solution is available, you can try one of three things:
- Use [virtualenv](http://pypi.python.org/pypi/virtualenv). This is what I normally use when working with Python. If you're using bash, I also recommend using [virtualenvwrapper](http://www.doughellmann.com/docs/virtualenvwrapper/#introduction) which makes using virtualenvs even easier.
- Run the same command with sudo one time: `sudo piped -nc tutorial.yaml -D`. This should allow Twisted to write the dropin.cache files, which should prevent it from having to write these cache files again. After running it with sudo once, you should then be able to run it without sudo privileges.
- Give your current user write access or ownership of the piped source directories: `sudo chown -R yourusername: /usr/lib/python2.6/site-packages/piped-0.1.0-py2.6.egg`.

I realize these options are not optimal, and I will take a closer look at this and find a better, permanent solution after this weekend.

**Comment by nkvoll** [comment]
I've researched this a bit, and it is definitely an issue with the Twisted version you're using. See [Twisted issue #2409](http://twistedmatrix.com/trac/ticket/2409). It has been fixed in the latest version of Twisted.

Can you upgrade your Twisted to 11.0 and try again? (`easy_install Twisted==11.0`)

**Comment by martinvilu** [comment]
I first used a clean virtualenv with the latest versions but did not work either
Sudo did the trick. I'll try to research the source of the problem.
So far, it seems like a problem with the Twisted plugin system.
Freezed packages in use

```
FormEncode==1.2.4
PyYAML==3.10
SQLAlchemy==0.7.1
Twisted==11.0.0
argparse==1.2.1
mock==0.7.2
mocker==1.1
networkx==1.5
ordereddict==1.1
piped==0.1.0
piped.contrib.database==0.1.0
piped.contrib.manhole==0.1.0
piped.contrib.status-testing==0.1.0
piped.contrib.validation==0.1.0
piped.contrib.zmq==0.1.0
pyOpenSSL==0.12
pyasn1==0.0.13b
pycrypto==2.3
pyzmq==2.1.7
zope.interface==3.6.3
```

**Comment by alexbrasetvik** [comment]
Should we bump the requirement for Twisted to >= 11.0?

We currently require >= 10.2 – though if you run Piped in the recommended way, i.e. with virtualenvs, then 10.2 suffices.

**Comment by nkvoll** [comment]
Bumped the version requirement for Twisted to >= 11.0 in version 0.2.0, which was just released.

https://github.com/foundit/Piped/commit/737761e108950e6280d844206eb14dbe9e596413
